firestore/index.html, firestore/test.firestore.js
@abehaskins @morganchen12 this is my best attempt at integrating array_contains into the cities data set in a not-awkward way.  What do you think?
If it looks good, I will duplicate for Android and iOS.
=> Add array data and queries

database/emulator-suite.js, firestore/emulator-suite.js
=> Emulator snippets for Web SDK to pull into Firesite

installations/index.js, installations/package.json
Add snippets for the installation SDK.
=> add installation snippets

.github/workflows/test.yml, .gitignore, README.md, auth/link-multiple-accounts.js, auth/package.json, database/emulator-suite.js, database/package.json, database/read-and-write.js, firebaseapp/firebaseapp.js, firestore/index.html, firestore/package.json, firestore/test.firestore.js, firestore/test.solution-aggregation.js, firestore/test.solution-arrays.js, firestore/test.solution-counters.js, functions/emulator-suite.js, functions/package.json, installations/index.js, installations/package.json, package.json, scripts/test.sh, tsconfig.json.template
Note: `installations` does not compile
=> Add compilation checks

auth/apple.js, auth/auth-state-persistence.js, auth/cordova.js, auth/custom-email-handler.js, auth/email-link-auth.js, auth/firebaseui.js, auth/google-signin.js, auth/index.js, auth/microsoft-oauth.js, auth/package.json, auth/service-worker-sessions.js, auth/yahoo-oauth.js, tsconfig.json.template
These were previously hardcoded on devsite.
cc @egilmorez this moves some of the current Auth snippets to GitHub.  No vNext yet.
=> Move some auth snippets

auth/facebook.js, auth/google-signin.js
See firebase/quickstart-js#502
Moving from snippets from quickstart-js to snippets-web
=> Bring in some more auth snippets

installations/index.js
Tag had no END tag. This fixes the typo.
=> Fix include tag typo

database/index.js, database/lists-of-data.js, database/read-and-write.js, database/sharding.js
=> Database snippets

firestore-next/test.firestore.js, firestore/test.firestore.js
Googlers: for context see http://b/176971059
=> Cloud Firestore --> Firestore

auth-next/email.js
Simple typo on line 33, nothing major
=> Simple typo

lerna.json, messaging/index.js, messaging/package.json, messaging/service-worker.js, storage/index.js, storage/package.json
This is the final move of snippets from quickstart-js to snippets-web
=> Move quickstart snippets

auth/email.js
i just changed out the typo on line 24
=> Changed typo error

analytics-next/package.json, auth-next/package.json, database-next/package.json, firebaseapp-next/package.json, firestore-next/package.json, functions-next/package.json, messaging-next/package.json, perf-next/package.json, remoteconfig-next/package.json, storage-next/package.json
https://www.npmjs.com/package/firebase/v/9.0.0-beta.1
=> vNext beta release

.gitignore, auth-next/manage.js
I created a new file namely `manage.js` as these functions are in "Manage Users" section in the documentation.
=> Added updateProfile and updateEmail for modular SDK

messaging-next/service-worker.js, snippets/messaging-next/service-worker/messaging_on_background_message.js
See:
https://firebase.google.com/docs/cloud-messaging/js/receive#setting_notification_options_in_the_service_worker
cc @egilmorez
=> Add messaging sw snippet

analytics-next/package.json, appcheck-next/package.json, auth-next/package.json, database-next/package.json, firebaseapp-next/package.json, firestore-next/package.json, functions-next/package.json, messaging-next/package.json, perf-next/package.json, remoteconfig-next/package.json, storage-next/package.json
@jhuleatt @kroikie @Feiyang1 any idea why this is failing?
=> Move to v9 stable release

auth/manage.js
Sources
- https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/model/user.ts#L85
- https://firebase.google.com/docs/reference/js/v8/firebase.User#getidtoken
- https://firebase.google.com/docs/reference/js/auth.user.md#usergetidtoken
- https://firebase.google.com/docs/auth/web/manage-users#get_a_users_profile
=> Update method in comment for getting the id token

firestore-next/test.firestore.js, snippets/firestore-next/test-firestore/fs_collection_group_query_data_setup.js
Call `addDoc(collection(` instead of `setDoc(doc(`, to ensure docs get added
=> Fix nesting issue in collection group query sample

auth/manage.js
Fix tiny typo in auth code sample
=> Fix tiny typo

auth-next/email-link-auth.js, snippets/auth-next/email-link-auth/email_link_complete.js
Update the comments on how to access the logged in user in v9 auth.
=> Update outdated comments
