firebase/snippets-web

- firestore/test.firestore.js
The code sample here suggests that the developer should use the promise returned from enablePersistence() to get a hold of a new Firestore instance when the promise resolves successfully.  This isn't a requirement, as subsequent queries are supposed to be enqueued to execute after enablePersistence is complete, in either success or failure cases.
> Be clear more clear about results of enablePersistence()

- CONTRIBUTING.md
- firestore/index.html
- firestore/test.firestore.js
`firebase.firestore.FieldValue` was released in version [5.9.0](https://firebase.google.com/support/release-notes/js#version_590_-_mar_14_2019) of the JS SDK
Added snippet and updated JS SDK version in samples. Also made a minor fix to Contributing.md
> Add field increment

- firestore/index.html
- firestore/test.firestore.js
Fix mocha tests. Bump version to pick up newer methods. Run cache size test earlier to fix this error:
> FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only call settings() before calling any other methods on a Firestore object.
> Bump sdk version. Run cache size test earlier.

- firestore/test.firestore.js
The [sample data](https://github.com/firebase/snippets-web/blob/master/firestore/test.firestore.js#L395) shows the field is named "regions", not "region"
> Fix sample data "regions" field typo

- installations/index.js
Other snippets for installations auth token is called `installationToken` using that here instead.
> Use consistent auth token variable

- auth/anonymous.js
- auth/custom.js
- auth/email-link-auth.js
- auth/email.js
- auth/facebook.js
- auth/index.js
See https://github.com/firebase/quickstart-js/pull/502
Moving from snippets from `quickstart-js` to `snippets-web`
> Move some auth snippets from quickstart-js

- firestore-next/test.solution-geoqueries.js
- firestore/test.solution-geoqueries.js
- snippets/firestore-next/test-solution-geoqueries/fs_geo_query_hashes.js
Looks like we have a `km` / `m` inconsistency.
Confirmation that `distanceBetween` is km:
```
$ node
> const geofire = require('geofire-common')
undefined
> const sf = [37.77, 122.42]
undefined
> const ny = [40.71, 74.00]
undefined
> geofire.distanceBetween(sf, ny)
4129.881115620339
```
Confirmation that `geohashQueryBounds` takes meters:
```
$ node
> const geofire = require('geofire-common')
undefined
> const sf = [37.77, -122.42]
undefined
> geofire.geohashQueryBounds(sf, 50000)
[ [ '9q8h', '9q8~' ],
[ '9q9h', '9q9~' ],
[ '9qb0', '9qbh' ],
[ '9qc0', '9qch' ] ]
```
Using https://geohash.co I can see that `9q8h` is `37.35351563, -123.57421875` and if we enter that in Google Maps we can see it's ~50km outside of San Francisco:
> Fix geofire meters / km mixup

- analytics-next/package.json
- auth-next/package.json
- database-next/package.json
- firebaseapp-next/package.json
- firestore-next/package.json
- functions-next/package.json
- messaging-next/package.json
- perf-next/package.json
- remoteconfig-next/package.json
- storage-next/package.json
The `ncu` script that we use for updates doesn't include `beta` versions by default so we have to do this manually.
> SDK v9.0.0-beta.3

- database-next/read-and-write.js
- snippets/database-next/read-and-write/rtdb_social_write_fan_out.js
In the firebase documentation for writing and reading data there is a code snippet (the only one actually) that does not have the necessary imports. I spent a few hours on stack overflow looking for the problem because I was getting errors in my React Native app, but it was actually the documentation that did not say I had to do the imports.
The snippet is in the "Updating or deleting data" section
https://firebase.google.com/docs/database/web/read-and-write#updating_or_deleting_data
> adding missing code in a snippet

- auth-next/apple.js
- auth/apple.js
- scripts/separate-snippets.ts
- snippets/auth-next/apple/auth_apple_nonce_node.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- firestore-next/test.firestore.js
- snippets/firestore-next/test-firestore/start_doc.js
> fix typo: popuation --> population

- analytics-next/index.js
- snippets/analytics-next/index/analytics_log_event_params.js
There's an error in the Analytics docs [here](https://firebase.google.com/docs/analytics/events?platform=web#log_events_5). The code snippet is for the `select_content` event, but in the Events [documentation](https://developers.google.com/analytics/devguides/collection/ga4/reference/events#select_content), `select_content` doesn't have `items`. This PR removes `items`.
> analytics select_content should not have items

- messaging/service-worker.js
Update service-worker snippet with correct v8 url
Referenced in issue https://github.com/firebase/firebase-js-sdk/issues/7030
> Update gstatic url for v8 example

- auth-next/index.js
- auth/index.js
- firestore/test.firestore.js
- scripts/separate-snippets.ts
- snippets/auth-next/index/auth_current_user.js
- snippets/auth-next/index/auth_state_listener.js
Closes #341 
This PR should:
- Fix broken v8 ref doc urls:
- `js/firebase.User` --> `js/v8/firebase.User`
- `js/firebase.firestore.GetOptions` --> `js/v8/firebase.firestore.GetOptions`
- Update the separate-snippets.ts script to properly map v8 urls to v9 when generating the modular snippets.
> fix broken ref docs urls

- auth-next/index.js
- database-next/read-and-write.js
- snippets/auth-next/index/auth_set_language_code.js
- snippets/database-next/read-and-write/rtdb_social_listen_star_count.js
This PR is to add a whitespace into an example script.
> chore: add missing whitespace & fix an incorrect snippet

- auth-next/package.json
- auth-next/phone-auth.js
- snippets/auth-next/phone-auth/auth_phone_recaptcha_verifier_invisible.js
- snippets/auth-next/phone-auth/auth_phone_recaptcha_verifier_simple.js
- snippets/auth-next/phone-auth/auth_phone_recaptcha_verifier_visible.js
RecaptchaVerifier param order is changing in v10 release of the web SDK, as seen in [this PR](https://github.com/firebase/firebase-js-sdk/pull/7326). This fix updates the web snippets to match this change.
> Update phone auth snippets with RecaptchaVerifier parameter reordering

- firestore-next/test.firestore.js
- firestore/test.firestore.js
- snippets/firestore-next/test-firestore/array_contains_any_filter.js
- snippets/firestore-next/test-firestore/in_filter_with_array.js
Fixes https://github.com/firebase/firebase-js-sdk/issues/7750.
> fix broken array-in snippets

- messaging/service-worker.js
We haven't updated the version since v9+ uses ESM syntax which isn't supported in service workers. We should update this version, but instead point to the compat packages since those use the namespaced API.
> Upgrade versions in FCM service worker

- remoteconfig-next/index.js
- snippets/remoteconfig-next/index/rc_set_minimum_fetch_time.js
This PR is to address the bug in documentation mentioned in https://github.com/firebase/firebase-js-sdk/issues/2841. Developers are assuming that the value we provided is the recommended prod min fetch interval and running into throttling issues.
> RC doc update to provide default prod value for minimumFetchIntervalMillis

- auth-next/email-link-auth.js
- snippets/auth-next/email-link-auth/auth_email_link_actioncode_settings.js
Update email link sign-in snippet to stop using `dynamicLinkDomain` as it's being deprecated.
Snippet used in https://firebase.google.com/docs/auth/web/email-link-auth#send_an_authentication_link_to_the_users_email_address.
> Update email link auth snippet to stop using deprecated `dynamicLinkDomain`
